# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PTBO Game Jam
email: hello@ptbogamejam.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://staging.ptbogamejam.com" # the base hostname & protocol for your site

dotbunny_url: "http://dotbunny.com"
dotbunny_api_url: "https://api.dotbunny.com"

meetup_url: "http://www.meetup.com/PTBOGameDev/"
forum_url: "http://forum.dotbunny.com/forums/gamejam/"
registration_url: "http://something"

username: "PTBOGameJam"

# Build settings
markdown: kramdown

google_api_key: "AIzaSyDtYuwLCEBRLorbWUdeCgHZjqOqM92Mjg4"


# Next Event Details
event_title: "PTBO Game Jam 02"

map_latitude: "40.6700"
map_longitude: "-73.9400"
map_zoom: "11"

venue_latitude: "40.6700"
venue_longitude: "-73.8400"
