# Jekyll settings
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: "/blog/page/:num/"
permalink: /blog/:year/:month/:day/:title/
version: 1.0.0

# Show Future Posts
future: true

# Site settings
title: PTBO Game Jam
email: "hello@ptbogamejam.com"
description: > # this means to ignore newlines until "baseurl:"
  The PTBO Game Jam is a gathering of industry professionals, students, hobbyists and those eager to learn creating video games in a short fixed period of time.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://staging.ptbogamejam.com" # the base hostname & protocol for your site

dotbunny_url: "http://dotbunny.com"
dotbunny_api_url: "https://api.dotbunny.com"

meetup_url: "http://www.meetup.com/PTBOGameDev/"
forum_url: "http://forum.dotbunny.com/forums/gamejam/"
registration_url: "http://ptbogamejam02.eventbrite.ca"

username: "PTBOGameJam"

# Build settings
markdown: kramdown

google_analytics: "UA-11332795-6"
google_api_key: "AIzaSyDtYuwLCEBRLorbWUdeCgHZjqOqM92Mjg4"
volunteer_email: "mailto:ptbogamejam@gmail.com?subject=I%20want%20to%20Volunteer!"

tag_page: '/blog/tags/'
category_page: '/blog/categories/'

titlebar: "title-001.jpg"

# Next Event Details
event_title: "PTBO Game Jam 02"
event_ics: "/content/ics/PTBOGameJam02.ics"
event_date_long: "February 2017"

map_latitude: "40.6700"
map_longitude: "-73.9400"
map_zoom: "11"

venue_latitude: "40.6700"
venue_longitude: "-73.8400"

press_name: "Matthew Davey"
press_email: "matthew.davey@dotbunny.com"
press_phone: "+1 (888) 632-1993 x700"
press_kit: "/press/PTBOGameJam_PressKit.zip"
brand_guidelines: "/press/brand-guidelines/"
media_releases: "/press/media-releases/"

stats_prizes: "4"
stats_games: "11"
stats_pizza: "78"
stats_sleep: "0"
stats_staff: "5"
stats_volunteers: "2"
