# Jekyll settings
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  input: GFM

excerpt_separator: "<!-- more -->"


# Exclude Files
exclude:
  - google4535fa0e277ccf45.html
  - content/vendor/fontello/demo.html
  - content/vendor/fontello/README.txt
  - content/vendor/form-validator/form-test.html
  - content/vendor/form-validator/qunit.html


# Number of blog posts per page
paginate: 5

# Blog Paginiation Setup
paginate_path: "/blog/page/:num/"

# Blog Post Generation Pretty Link
permalink: /blog/:year/:month/:day/:title/

# Show Future Posts
future: true

# Site settings
title: PTBO Game Jam
email: "hello@ptbogamejam.com"
description: > # this means to ignore newlines until "baseurl:"
  The PTBO Game Jam is a gathering of industry professionals, students, hobbyists and those eager to learn creating video games in a short fixed period of time.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ptbogamejam.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

google_analytics: "UA-11332795-6"
google_api_key: "AIzaSyDtYuwLCEBRLorbWUdeCgHZjqOqM92Mjg4"
volunteer_email: "mailto:ptbogamejam@gmail.com?subject=I%20want%20to%20Volunteer!"

titlebar: "title-001.jpg"

# Next Event Details

map_latitude: "40.6700"
map_longitude: "-73.9400"
map_zoom: "11"

venue_latitude: "40.6700"
venue_longitude: "-73.8400"

press_prefix: "He"
press_name: "Matthew Davey"
press_email: "matthew.davey@dotbunny.com"
press_phone: "+1 (888) 632-1993 x700"
press_kit: "/files/branding/PTBOGameJam_PressKit.zip"
